name: Test 

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: docker build -t martintrajanovski/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run martintrajanovski/react-test npm run test -- --watchAll=false
